### ISSUE TITLE
mosaic error

### ISSUE THREAD

**Issue by jaycopeland** [sorgerlab/ashlar#10]
On my first attempt to use ashlar on O2 I ran into this: 

```
jc168@compute-a-16-69:~$ mosaic /n/scratch2/jc168/forZoltan/ZM_CYCIF1_051_Nicole3/
Scan 0:
Traceback (most recent call last):
  File "/n/groups/lsp/o2/apps/ashlar/1.0.3/venv/bin/mosaic", line 11, in <module>
    load_entry_point('ashlar==1.0.3', 'console_scripts', 'mosaic')()
  File "/n/groups/lsp/o2/apps/ashlar/1.0.3/venv/lib/python2.7/site-packages/ashlar/scripts/mosaic.py", line 18, in main
    print '    reading %s' % filepaths[0]
IndexError: list index out of range
jc168@compute-a-16-69:~$
 ```

Does the input require that specify more than the containing directory?

**Comment by jmuhlich** [comment]
The input should be either of the following:

1. A single directory, containing a number of .rcpnl files. To use this option, the files must be named so that their lexicographic ordering matches their cycle order. For example "Cycle1", "Cycle2" ... "Cycle10" is no good. "Cycle01" ... "Cycle10" would be OK. "Scan_YYYYMMDD_HHMMSS_..." is also OK.

2. An explicit list of .rcpnl files. This form is useful if you want to process only a subset of cycle files in a directory, or if you need to handle the "Cycle1" naming convention mentioned above. For the latter, I use this pattern:

  mosaic /path/to/sample/Cycle{?,??}.rcpnl 

Did your `ZM_CYCIF1_051_Nicole3` folder contain a list of .rcpnl files?

**Comment by jmuhlich** [comment]
Closing due to lack of further details.
